### ISSUE TITLE
Key images as buttons?

### ISSUE THREAD

**Issue by 130s** [WPI-RAIL/keyboardteleopjs#12]
First of all, nice tool!

I'm just wondering if there is any plan to make the images of the key as button?

Someone implemented a web app using `keyboardteleopjs`.  
![Key images](http://wiki.ros.org/keyboardteleopjs?action=AttachFile&do=get&target=example.png)
When I first saw this image on the browser, I tried to click the images and it took me a few minutes to start using keyboard. The image definitely helps, but it was still confusing. 

I'm not sure if I can have an extra gear soon to try making a pull req for this...

**Comment by rctoris** [comment]
The library itself is only meant to bind key commands. That image came off of the wiki: http://wiki.ros.org/keyboardteleopjs. I'm not sure building such a thing into the library makes sense as it would require the image/DOM elements to be incorporated into the lib. I think if such a thing was desired a standalone tool could be used.

**Comment by 130s** [comment]
Makes sense. We'll then try making something that'll be based on `keyboardteleopjs`.
