### ISSUE TITLE
Shouldn't example use localhost?

### ISSUE THREAD

**Issue by jrlandau** [WPI-RAIL/keyboardteleopjs#15]
Line 22 of the script says

22       url : 'ws://rail-sim2.cs.wpi.edu:9090'

Shouldn't this be using localhost instead, as

22       url : 'ws://localhost:9090'    ?

I am still unable to get the example working:  The code seems to execute but the PR2 does not move.  Any help would be appreciated.

**Comment by rctoris** [comment]
Which branch/version are you using? Looks like the example code is using localhost: https://github.com/WPI-RAIL/keyboardteleopjs/blob/develop/examples/keyboardteleop.html#L25

Are you using this with gazebo? Are the commands coming through?

`rostopic echo /base_controller/command`

**Comment by jrlandau** [comment]
I have been using the version at

http://wiki.ros.org/keyboardteleopjs/Tutorials/CreatingABasicTeleopWidgetWithSpeedControl

Apparently it is downlevel.

I will try again with the example code you indicate on GitHub and "rostopic
echo"

**Comment by jrlandau** [comment]
After cloning the develop branch, I rewrote several script references in
the example as they have a dependency on the folder hierarchy that the
browser sees as the current directory.  (i.e., they contained "../").  I
hope I got that right.  Are these libraries different from the ones on the
CDN that were used by the tutorial I originally used?

Using Firefox, I could not use the debugger; it interfered with the
script's operation.  Finally after closing the debugger I got messages of
the form showing 2 vectors in 3-space each time I pressed the arrow key.

I also got messages like the following, which may have followed the vector
messages.

[WARN] [WallTime: 1427239094.065994] [63.341000] Could not process inbound
connection: Internal error processing topic
[/base_controller/command]{'message_definition': '# This expresses velocity
in free space broken into its linear and angular parts.\nVector3
linear\nVector3
angular\n\n================================================================================\nMSG:
geometry_msgs/Vector3\n# This represents a vector in free space.
\n\nfloat64 x\nfloat64 y\nfloat64 z\n', 'callerid':
'/rostopic_13423_1427238925281', 'tcp_nodelay': '0', 'md5sum':
'9f195f881246fdfa2798d1d3eebca84a', 'topic': '/base_controller/command',
'type': 'geometry_msgs/Twist'}

The PR2 still has not moved.

**Comment by jrlandau** [comment]
Here are the echoes that I get:
linear:
  x: 0.0
  y: 0.0
  z: -0.87
angular:
  x: 0.0
  y: 0.0

##   z: -0.87

linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0

The PR2 still does not move.

Thanks,

Joe

**Comment by rctoris** [comment]
Hmmm strange, if the echos are coming through then the messages are indeed making it through rosbridge and into the ROS system itself. Are you able to move the PR2 within ROS itself? I'm not too familiar with the PR2 gazebo environment anymore but you may be able to launch the pr2 simple keyboard teleop node (http://wiki.ros.org/pr2_teleop). I know in some versions of Gazebo too you must first unpause the simulation.

What version of ROS/rosbridge_suite are you using?

**Comment by jrlandau** [comment]
I'm using hydro, on Ubuntu 12.04.

At present I am unable to see PR2 moving at all.  At the moment, I am going
to back off and study what I have so far--I need to learn more about ROS,
and Javascript too.  Perhaps I will try a different simulator.

My ultimate objective is to add voice control capability to teleop.

Joe

**Comment by jrlandau** [comment]
Hello Russell,

I'm making progress on my project (teleop with speech) but have run into a
little snag.  Google speech recognition runs awkwardly if the page is not
accessed with https.  This requirement evidently applies to referenced
libraries, too. So I should use https.

My references to
 <script type="text/javascript" src="
https://cdn.robotwebtools.org/EventEmitter2/current/eventemitter2.min.js">
and
    <script type="text/javascript" src="
https://cdn.robotwebtools.org/roslibjs/current/roslib.js">
do not work; I am getting "net::ERR_INSECURE_RESPONSE"

Am I doing something wrong, or is it simply that this cdn does not support
https?

Thanks,

Joe

**Comment by rctoris** [comment]
We don't have SSL certs on the actual CDN domain. You can access them securely though directly through their AWS S3 URL, e.g., https://s3.amazonaws.com/cdn.robotwebtools.org/roslibjs/current/roslib.min.js

**Comment by jrlandau** [comment]
Thanks, that did the trick.  Of course, it exposed the next problem:  the
websocket connection to the robot.

Mixed Content: The page at 'https://10.0.0.21/teleop-widget.html' was
loaded over HTTPS, but attempted to connect to the insecure WebSocket
endpoint 'ws://10.0.0.21:9090/'. This request has been blocked; this
endpoint must be available over WSS.

I tried WSS, but that was refused.

WSS would have to be a feature of rosbridge, right?  Is there a way to do
that?

**Comment by rctoris** [comment]
There is -- the launch file in rosbridge has an SSL flag that defaults to false which will start the server over wss. You can set it to true but you'll need provide an SSL certificate as well (you'll see the parameters in the launch file).

**Comment by rctoris** [comment]
Oops, forgot to link the launch file: https://github.com/RobotWebTools/rosbridge_suite/blob/develop/rosbridge_server/launch/rosbridge_websocket.launch#L4

**Comment by jrlandau** [comment]
Thanks.

It's also maybe worth noting that the wss connection to the robot is
rejected if the certificate is self-signed.  The workaround that worked for
me was to first access the robot's address manually (https).  In that case
you get a message and a chance to accept the presumed insecurity.  After
that, the wss connection worked.
